# config.yaml

aws:
  bedrock:
    region: us-east-1
    temperature: 0.7
    max_tokens: 500

logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s: %(message)s"

agent:
  name: red_agent
  model_id: anthropic.claude-v2
  port: 8000
  host: 0.0.0.0

llm:
  provider: bedrock
